# Generated by Django 2.2.3 on 2019-07-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('flat_no', models.CharField(blank=True, default=None, max_length=5, null=True, unique=True)),
                ('phone1', models.IntegerField(blank=True, default=None, null=True, unique=True)),
                ('phone2', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('status', models.CharField(choices=[('O', 'Owner'), ('T', 'Tenant'), ('V', 'Vacant')], default=None, max_length=1)),
                ('corpus_due', models.IntegerField(blank=True, default=None, null=True)),
                ('corpus_due_date', models.DateField(blank=True, default=None, null=True)),
                ('membership_due', models.IntegerField(blank=True, default=None, null=True)),
                ('membership_due_date', models.DateField(blank=True, default=None, null=True)),
                ('legal_charges_due', models.IntegerField(blank=True, default=None, null=True)),
                ('legal_charges_due_date', models.DateField(blank=True, default=None, null=True)),
                ('consumer_due', models.IntegerField(blank=True, default=None, null=True)),
                ('consumer_due_date', models.DateField(blank=True, default=None, null=True)),
                ('maintenance_due', models.IntegerField(blank=True, default=None, null=True)),
                ('maintenance_due_date', models.DateField(blank=True, default=None, null=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
